# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-23 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.TextField(default='', max_length=50)),
                ('upperEmail', models.EmailField(default='', max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('phone', models.TextField(default='', max_length=15)),
                ('depot', models.TextField(default='', max_length=10)),
                ('email', models.TextField(default='', max_length=50)),
                ('permission', models.CharField(max_length=3)),
                ('eaTime', models.TimeField()),
                ('eaPermission', models.CharField(default='111', max_length=3)),
                ('dataOpen', models.IntegerField(default=0)),
            ],
        ),
    ]
